apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: abdulrehmanconq/auth-service
          ports:
            - containerPort: 3000
          env:
            - name: SUPABASE_URL
              value: https://tyvfcvzhckirmlssnedd.supabase.co
            - name: SUPABASE_ANNON_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dmZjdnpoY2tpcm1sc3NuZWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTI5NzEwOTQsImV4cCI6MjAwODU0NzA5NH0.HQW7rnzKgVb6Q95GxHYlbtipYpCryWu8wuPj54XKEh0
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    component: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
