apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth-postgres-service
  template:
    metadata:
      labels:
        component: auth-postgres-service
    spec:
      volumes:
        - name: auth-postgres-storage
          persistentVolumeClaim:
            claimName: auth-postgres-pvc
      containers:
        - name: auth-postgres-service
          image: postgres:alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: auth-postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: auth-postgres-service
  ports:
    - name: auth-postgres-service
      port: 5432
      targetPort: 5432
      protocol: TCP
